### ISSUE TITLE
Exception: OCR init fail.

### ISSUE THREAD

**Issue by JiahuaLink** [hiroi-sora/PaddleOCR-json#46]
Traceback (most recent call last):
  File "threading.py", line 950, in _bootstrap_inner
  File "threading.py", line 888, in run
  File "keyboard\_generic.py", line 58, in process
  File "keyboard\__init__.py", line 218, in pre_process_event
  File "keyboard\__init__.py", line 649, in <lambda>
  File "main.py", line 135, in show_message
  File "question_to_answer.py", line 21, in __init__
  File "ocr_api.py", line 47, in __init__
Exception: OCR init fail.  
请问我的代码打包为pyinstaller的时候运行会报错，但是本地运行是ok的

**Comment by hiroi-sora** [comment]
抱歉现在才看到你的问题。你这个问题是将引擎组件打包进pyinstaller后，引擎读取模型库的路径不正确，导致无法完成初始化。

C++引擎组件需要读取导入模型库。默认情况下（未pyinstaller打包），它读取相对路径子文件夹中的模型库文件。如果通过pyinstaller打包，pyinstaller会在执行时将引擎组件解压到一个系统临时路径，这样可能导致引擎无法读取模型库。

不建议通过pyinstaller连同引擎一起打包为单个文件，而是只打包 python API 部分，将引擎放在外部，当作外部文件访问。
