### ISSUE TITLE
关于pyinstaller 封装exe的问题

### ISSUE THREAD

**Issue by handouy** [hiroi-sora/PaddleOCR-json#89]
请问下大佬这个项目支持pyinstaller 封装吗 
如果可以的话 大概需要什么步骤呢
我按照常规流程打包进程序 识别图片报错
Exception in thread Thread-4 (on_paste):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "test.py", line 516, in on_paste
  File "test.py", line 491, in handle_clipboard_image
  File "PaddleOCR.py", line 13, in paddleocr
  File "C:\Users\1\AppData\Local\Temp\_MEI403002\PPOCR_api.py", line 198, in GetOcrApi
    return PPOCR_pipe(exePath, argument)
  File "C:\Users\1\AppData\Local\Temp\_MEI403002\PPOCR_api.py", line 35, in __init__
    self.ret = subprocess.Popen(  # 打开管道
  File "subprocess.py", line 971, in __init__
  File "subprocess.py", line 1456, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
Exception ignored in: <function PPOCR_pipe.__del__ at 0x000002155E669090>
Traceback (most recent call last):
  File "C:\Users\1\AppData\Local\Temp\_MEI403002\PPOCR_api.py", line 121, in __del__
    self.exit()
  File "C:\Users\1\AppData\Local\Temp\_MEI403002\PPOCR_api.py", line 102, in exit
    self.ret.kill()  # 关闭子进程
AttributeError: 'PPOCR_pipe' object has no attribute 'ret'

**Comment by hiroi-sora** [comment]
你的报错： `FileNotFoundError: [WinError 2] 系统找不到指定的文件` ，表示程序无法找到 `PaddleOCR-json.exe` 的正确路径。

从spec配置文件看，你似乎想把 `PaddleOCR-json_v.1.3.1` 整个目录打包进exe中。这样做**理论上可行**，但实际使用时会有诸多问题。

pyinstaller打包单文件的原理，实际上是创建了一个压缩包。在每次运行时，将所有文件解压到C盘一个临时目录，这个目录可以用环境变量`sys._MEIPASS`来获取。也就是，假设程序在 D:/aaa 运行，临时文件解压在 C:/bbb 。如果你依然从 `D:/aaa/PaddleOCR` 中寻找exe，这是不可能找到的，要在  `C:/bbb/PaddleOCR` 中寻找。

具体可以在网上找相关资料，如： https://www.zhihu.com/question/615583557

---

但是，“每次运行时解压大量文件”并不优雅，会拖慢程序的启动。这也是为什么我家Umi-OCR v2.0 放弃pyinstaller的主要原因。如果你有必要使用pyinstaller，我建议还是：

1. 主程序exe中，只放置python代码，不打包`PaddleOCR-json` 。
2. 将 `PaddleOCR-json` 目录，放置在exe的同一文件夹中。
3. 如果有需要生成单文件exe，可以将上述所有文件，打包为自解压exe包。

**Comment by handouy** [comment]
谢谢大佬解答 懂了懂了！
